// AUTO-GENERATED by scripts/stampVersion.js -- DO NOT EDIT BY HAND.
// This file is regenerated on every `npm run dev` and `npm run build`,
// so any manual edits here will be overwritten on the next stamp.
//
// To bump the version, just commit. The patch number is the current commit
// count and the short SHA is the current HEAD.

export const APP_VERSION_SEMVER = "1.0.181";
export const APP_VERSION_LABEL = "v1.0.181+dirty BETA · d4c28b9";
export const APP_VERSION_SHA = "d4c28b9";
export const APP_VERSION_DATE = "2026-07-03 09:31 UTC";
