#!/usr/bin/env node
/**
 * Auto-stamps utils/version.ts with the current build identity so the
 * dashboard logo always shows a version that increments per commit.
 *
 * Runs as a `prebuild` and `predev` hook so that:
 *   - `npm run build`  -> stamps fresh version, then builds
 *   - `npm run dev`    -> stamps fresh version, then runs dev server
 *
 * What gets stamped:
 *   - APP_VERSION_SEMVER  e.g. "1.0.42"   (1.0.<commit-count-on-main>)
 *   - APP_VERSION_LABEL   e.g. "v1.0.42 BETA · a2b92c2"  (logo display)
 *   - APP_VERSION_SHA     short git SHA at stamp time
 *   - APP_VERSION_DATE    ISO-ish build timestamp (UTC)
 *
 * If git is unavailable for any reason, falls back to a sensible default
 * so the build never breaks just because we couldn't read git.
 */

const { execSync } = require('child_process');
const { writeFileSync } = require('fs');
const { resolve } = require('path');

function tryGit(cmd, fallback) {
    try {
        return execSync(cmd, { stdio: ['ignore', 'pipe', 'ignore'] })
            .toString()
            .trim();
    } catch {
        return fallback;
    }
}

function buildVersion() {
    // Commit count is monotonically increasing across the project's history,
    // which is exactly what we want for "bumps each release". We pin the
    // major/minor at 1.0 and let the patch number track commits — so v1.0.42
    // is meaningfully "the 42nd commit-worth of progress".
    const commitCount = tryGit('git rev-list --count HEAD', '0');
    const shortSha = tryGit('git rev-parse --short HEAD', 'unknown');
    const dirty = tryGit('git status --porcelain', '').length > 0;

    const semver = `1.0.${commitCount}`;
    const date = new Date().toISOString().replace('T', ' ').slice(0, 16) + ' UTC';
    const dirtyMarker = dirty ? '+dirty' : '';
    const label = `v${semver}${dirtyMarker} BETA · ${shortSha}`;

    return { semver, label, sha: shortSha, date };
}

function main() {
    const v = buildVersion();
    const out = `// AUTO-GENERATED by scripts/stampVersion.js -- DO NOT EDIT BY HAND.
// This file is regenerated on every \`npm run dev\` and \`npm run build\`,
// so any manual edits here will be overwritten on the next stamp.
//
// To bump the version, just commit. The patch number is the current commit
// count and the short SHA is the current HEAD.

export const APP_VERSION_SEMVER = ${JSON.stringify(v.semver)};
export const APP_VERSION_LABEL = ${JSON.stringify(v.label)};
export const APP_VERSION_SHA = ${JSON.stringify(v.sha)};
export const APP_VERSION_DATE = ${JSON.stringify(v.date)};
`;

    const target = resolve(__dirname, '..', 'utils', 'version.ts');
    writeFileSync(target, out);
    console.log(`[stampVersion] ${v.label}  (${v.date})`);
}

main();
